// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/deadlines": {
            "get": {
                "description": "Returns all regulatory deadlines",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deadlines"
                ],
                "summary": "List regulatory deadlines",
                "responses": {
                    "200": {
                        "description": "Example: {\\\"code\\\":\\\"A00\\\",\\\"message\\\":\\\"success\\\",\\\"data\\\":[]}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Example payload:\n{\n\"title\": \"Quarterly BAS Lodgement\",\n\"category\": \"ATO_TAX\",\n\"dueDate\": \"2025-01-31\",\n\"notes\": \"Coordinate with accountant\"\n}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deadlines"
                ],
                "summary": "Create a new regulatory deadline",
                "parameters": [
                    {
                        "description": "Deadline payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Example: {\\\"code\\\":\\\"A00\\\",\\\"message\\\":\\\"success\\\",\\\"data\\\":{}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/deadlines/{id}/complete": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deadlines"
                ],
                "summary": "Mark a deadline as completed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deadline ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Example: {\\\"code\\\":\\\"A00\\\",\\\"message\\\":\\\"success\\\",\\\"data\\\":{}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Regulatory Deadline Calendar API",
	Description:      "Simple in-memory API to track regulatory deadlines for startups in Australia.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
